export enum BetAmounts {
  "Floor" = "betf",
  "2x Floor" = "bet 2f",
  "All In" = "allin",
  "Half In" = "halfin",
  "10%" = "bet 10%",
  "25%" = "bet 25%",
}

export enum BetTargets {
  "Random" = "random",
  "Team 1" = "left",
  "Team 2" = "right",
  "Underdog" = "dog",
}

export enum Jobs {
  "Squire" = "Squire",
  "Chemist" = "Chemist",
  "Knight" = "Knight",
  "Archer" = "Archer",
  "Monk" = "Monk",
  "Priest" = "Priest",
  "Wizard" = "Wizard",
  "Time Mage" = "TimeMage",
  "Summoner" = "Summoner",
  "Thief" = "Thief",
  "Mediator" = "Mediator",
  "Oracle" = "Oracle",
  "Geomancer" = "Geomancer",
  "Lancer" = "Lancer",
  "Samurai" = "Samurai",
  "Ninja" = "Ninja",
  "Calculator" = "Calculator",
  "Dancer" = "Dancer",
  "Bard" = "Bard",
  "Mime" = "Mime",
}

export enum Monsters {
  "Dark Behemoth" = "DarkBehemoth",
  "Ultima Demon" = "UltimaDemon",
  "Tiamat" = "Tiamat",
  "Holy Dragon" = "HolyDragon",
  "Steel Giant" = "SteelGiant",
  "Red Dragon" = "RedDragon",
  "Red Chocobo" = "RedChocobo",
  "Archaic Demon" = "ArchaicDemon",
  "Blue Dragon" = "BlueDragon",
  "King Behemoth" = "KingBehemoth",
  "Dragon" = "Dragon",
  "Serpentarius" = "Serpentarius",
  "Hydra" = "Hydra",
  "Wyvern" = "Wyvern",
  "Byblos" = "Byblos",
  "Behemoth" = "Behemoth",
  "Apanda" = "Apanda",
  "Cockatrice" = "Cockatrice",
  "Sekhret" = "Sekhret",
  "Minotaur" = "Minotaur",
  "Bull Demon" = "BullDemon",
  "Coeurl" = "Coeurl",
  "Black Chocobo" = "BlackChocobo",
  "Vampire" = "Vampire",
  "Mindflayer" = "Mindflayer",
  "Taiju" = "Taiju",
  "Reaper" = "Reaper",
  "Explosive" = "Explosive",
  "Plague" = "Plague",
  "Draugr" = "Draugr",
  "Juravis" = "Juravis",
  "Wild Boar" = "WildBoar",
  "Treant" = "Treant",
  "Revenant" = "Revenant",
  "Skeleton" = "Skeleton",
  "Red Panther" = "RedPanther",
  "Grenade" = "Grenade",
  "Bomb" = "Bomb",
  "Porky" = "Porky",
  "Ghost" = "Ghost",
  "Ahriman" = "Ahriman",
  "Iron Hawk" = "IronHawk",
  "Gobbledeguck" = "Gobbledeguck",
  "Great Malboro" = "GreatMalboro",
  "Chocobo" = "Chocobo",
  "Black Goblin" = "BlackGoblin",
  "Dryad" = "Dryad",
  "Swine" = "Swine",
  "Ghoul" = "Ghoul",
  "Ochu" = "Ochu",
  "Goblin" = "Goblin",
  "Squidraken" = "Squidraken",
  "Pisco Demon" = "PiscoDemon",
  "Malboro" = "Malboro",
  "Floating Eye" = "FloatingEye",
}
